export const THEMES = [
    "light",
    "dark",
<<<<<<< HEAD
    // "cupcake",
    // "bumblebee",
    // "emerald",
    // "corporate",
    // "synthwave",
    // "retro",
    // "cyberpunk",
    // "valentine",
    // "halloween",
    // "garden",
    // "forest",
    // "aqua",
    // "lofi",
    // "pastel",
    // "fantasy",
    // "wireframe",
    // "black",
    // "luxury",
    // "dracula",
    // "cmyk",
    // "autumn",
    // "business",
    // "acid",
    // "lemonade",
    // "night",
    // "coffee",
    // "winter",
    // "dim",
    // "nord",
    // "sunset",
=======
>>>>>>> 510f87e432313ed8949c76490d3ebe86d2cf020b
  ];